version: '3'

services:
  db:
    image: postgres:14.0-alpine
    restart: always
    env_file:
       - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - "5432"
  web:
    build: .
    command: >
      bash -c "python manage.py migrate &&
               python manage.py runserver 0.0.0.0:8000"
    volumes:
      - project:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data:
  project: